### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by francqz31** [ddlBoJack/emotion2vec#12]
Hey Author , Thanks for the opensource

I wanted to ask if emotion2vec is better than https://github.com/audeering/w2v2-how-to
 
Thanks in advance

**Comment by ddlBoJack** [comment]
Hi, it is worth noting that emotion2vec is a universal emotional representation model, which needs to be trained on a certain downstream task to compare the performance. For performance on a specific dataset, please refer to our paper: https://arxiv.org/abs/2312.15185
We will provide a finetuned model with massive labeled data soon, welcome to follow up and compare performance :)

**Comment by ddlBoJack** [comment]
Our emotion2vec only has 12 layers of 768-dim transformer. As for the performance, researchers can explore further after we release the finetuned checkpoint.
