### ISSUE TITLE
Info about checkpoint file

### ISSUE THREAD

**Issue by basavarajsh98** [ddlBoJack/emotion2vec#13]
Hi @ddlBoJack,

Please share some information about the checkpoint file shared in the readme. Is it the best performing model so far?

Also the train.py file given for IEMOCAP, is it the frame-level or utterance level features?

Thanks,

**Comment by ddlBoJack** [comment]
Hi, we have listed the comparison of different models on different datasets in our paper, you can refer to it.
The frame-level features are used to train the downstream task. You can also get good results if you use utterance-level features.
