### ISSUE TITLE
Wechat Group application

### ISSUE THREAD

**Issue by coding-sharks** [ddlBoJack/emotion2vec#14]
Hello! One of my work recently used Emotion2Vec. Could I join this group chat to communicate with you? My wechat can be get by my profile picture(QR code) If you are not busy, you can get my wechat by scanning it! Thank you very much.

**Comment by coding-sharks** [comment]
![image](https://github.com/ddlBoJack/emotion2vec/assets/100142736/e530c8be-8bc6-412c-be54-945784030cf9)

**Comment by ddlBoJack** [comment]
Added
