### ISSUE TITLE
Two key models in finetune without annotated data

### ISSUE THREAD

**Issue by lhanzl** [ddlBoJack/emotion2vec#20]
非常感谢作者开源这么好的情绪预训练模型。

我在modelscope上看到有这样的描述：
首先使用语音情感识别学术数据集fine-tune emotion2vec，然后对15万小时中英数据进行标注，筛选文本情感与语音情感相同，并且置信度高的数据。
请问能否开源下文本情绪模型和采用学术数据集训练的语音情绪模型吗，我想基于此方法训练一个3分类模型。

谢谢！

**Comment by ddlBoJack** [comment]
We will update more checkpoints later. Please stay tuned!
