### ISSUE TITLE
Request for test and dev files

### ISSUE THREAD

**Issue by cyaaronk** [ddlBoJack/emotion2vec#25]
Dear Authors,

You have only shared the ```train.npy```, ```train.lengths```, ```train.emo``` in the ```iemocap_downstream``` folder.
Do you mind sharing also the test and dev versions of the files? This will make testing your models more convenient.

Thank you in advance.

Best regards,
Aaron

**Comment by ddlBoJack** [comment]
Hi, the standard IEMOCAP performance is tested using a leave-one-session-out five-fold cross-validation approach. With our training script, you will get five models, and the test script for each model is written in the training workflow. You can check here: https://github.com/ddlBoJack/emotion2vec/blob/d583d480f37e115fd4ef3e65f3d38d4050708477/iemocap_downstream/main.py#L85

**Comment by cyaaronk** [comment]
Thank you for the quick clarification.
