### ISSUE TITLE
About reproducing data2vec2 results

### ISSUE THREAD

**Issue by yqhao45** [ddlBoJack/emotion2vec#29]
When loading the data2vec2 model using fairseq. checkpoint_utils. load_model_ensemble_and_task ([ckpt_path]), an error occurred while loading the data2vec2 model: KeyError : "_name",  Could you please tell me how to solve the problem of loading the model

**Comment by ddlBoJack** [comment]
Which model do you mean?

**Comment by ddlBoJack** [comment]
I really did not get your idea. You mean, could not able to load the emotion2vec_base model with Fairseq load_model_ensemble_and_task method?

**Comment by yqhao45** [comment]
我不是要加载emotion2vec_base，我只是想要实现data2vec2的开源预训练模型做类似下游任务，在网络上看到你们有使用data2vec2做模型的对比对此很感兴趣，问一下你们在实验中是否遇到过fairseq模型加载的问题。

**Comment by ddlBoJack** [comment]
I do not remember problems like this, for it has been long since I set up the env. 
But I recommend that you check the following:
1. `pip install -e`for fairseq
2. export python path for fairseq
3. use `user_dir` in the command line

**Comment by yqhao45** [comment]
I have updated fairseq as you said, but I did not understand the user dir step here. If possible, I would like to add a WeChat message to you and send a detailed picture description. The official WeChat group's QR code has expired

**Comment by ddlBoJack** [comment]
WeChat QR updated
