### ISSUE TITLE
What is Emo-262?

### ISSUE THREAD

**Issue by Vincent-ZHQ** [ddlBoJack/emotion2vec#3]
What is the dataset Emo-262? Does your group collect it and will it be available for the public? How can I get it?

Hint: The word LSSED in the Table 2 caption is wrong and was written as LSED. Maybe you can check your paper writing.

**Comment by ddlBoJack** [comment]
Emo-262 is a collection of open-source datasets, and you can check details in our paper: https://arxiv.org/abs/2312.15185

And thank you for your correction of the LSSED dataset. We will revise it later.
