### ISSUE TITLE
Optimal segment length

### ISSUE THREAD

**Issue by LorantSzaboOxit** [ddlBoJack/emotion2vec#30]
Hello!

Thank you for such a nice work!

I am performing speaker diarization with _pyannote_, and want to use the audio segments which i recieve from the diarization model to perfrom emotion detection on them. The segments are of different sizes, I'm sure I'll have to do some kind of splitting because of the CUDA OOM for very long segments (like 200 sec), but I'm wondering what is the optimal segment size for the emotion2vec_plus_large model? 3 seconds, 15 seconds or whatever?

Thank you!

**Comment by ddlBoJack** [comment]
There is no definite length for the audio. You can get only one emotion label for the audio input, no matter how long your audio is. So you can cut the audio via VAD so it is complete at the semantic level.

**Comment by LorantSzaboOxit** [comment]
Thank you for your response.

The audio is already cut by the speaker diarization model, which also uses VAD. I would like to use these segments to do emotion detection with your model. Then these variable length segments do not require any further cutting, so if we pass them to the model in one piece, we can get the best results? What does utterance-level mean?

**Comment by ddlBoJack** [comment]
You can directly feed the variable length segments into the model, and the model can tackle variable length segments. In fact, the model is trained with variable length segments.

**Comment by LorantSzaboOxit** [comment]
Okay, thank you for your answers.
