### ISSUE TITLE
miss key in ckpt

### ISSUE THREAD

**Issue by wxjnb** [ddlBoJack/emotion2vec#40]
![屏幕截图 2024-07-26 165033](https://github.com/user-attachments/assets/ce36fb61-d082-4917-b275-aa03ab655a4c)

Hello, Could you please explain what this warning is about?

**Comment by SoshyHayami** [comment]
yeah, i also get this, very curios about

**Comment by ddlBoJack** [comment]
This warning is related to the FunASR repo, and you can just ignore it.
