### ISSUE TITLE
Why I only get 5 classes of emotion

### ISSUE THREAD

**Issue by Mahaotian1** [ddlBoJack/emotion2vec#45]
According to the official description, the motion2vec_plus model should be able to categorize speech into 9 classes, but why did I actually run it with only 5 classes（angry、happy、neutral、sad and <unk>）?

usage：
inference_pipeline = pipeline(
        task=Tasks.emotion_recognition,
        model="iic/emotion2vec_plus_base", 
        device = "gpu:1")
rec_result = inference_pipeline("/home/data2/tts_data/raw/opensrc/Emotion Speech Dataset/0007/Neutral/0007_000239.wav", output_dir="./cosyvoice_embedding", granularity="utterance", extract_embedding=False)

**Comment by LorantSzaboOxit** [comment]
emotion2vec_plus_seed/base/large works with 5 classes (angry, happy, neutral, sad, unk)

emotion2_vec_/base/large/base_finetuned works with 9 classes (angry, disgusted, fearful, happy, neutral, other, sad, surprised, unknown)

if i'm right

**Comment by ddlBoJack** [comment]
You can use this pipeline to get 9-class labels:
```
from funasr import AutoModel

model = AutoModel(model="iic/emotion2vec_plus_large")

wav_file = f"{model.model_path}/example/test.wav"
rec_result = model.generate(wav_file, output_dir="./outputs", granularity="utterance", extract_embedding=False)
print(rec_result)
```

**Comment by Mahaotian1** [comment]
> You can use this pipeline to get 9-class labels:
> 
> ```
> from funasr import AutoModel
> 
> model = AutoModel(model="iic/emotion2vec_plus_large")
> 
> wav_file = f"{model.model_path}/example/test.wav"
> rec_result = model.generate(wav_file, output_dir="./outputs", granularity="utterance", extract_embedding=False)
> print(rec_result)
> ```

it works，thanks a lot

**Comment by itaowei** [comment]
the `model_revision` in `pipeline()` should be set to `master` to use the latest model :)

```python
inference_pipeline = pipeline(
    task=Tasks.emotion_recognition,
    model="iic/emotion2vec_plus_large",
    model_revision = "master")
```

I just met the same problem, hhh
