### ISSUE TITLE
About feature layer

### ISSUE THREAD

**Issue by hayeong0** [ddlBoJack/emotion2vec#5]
Thank you for sharing your nice work! 

In the script `emotion2vec_extract_features.sh`, I noticed that features are extracted from the last layer. 
Have you tried extracting features from other layers as well?  
I'm just curious if this approach is based on empirical insight.

**Comment by ddlBoJack** [comment]
hi, thanks for the recognition of our work.

For most SSL models, using a weighted sum of multiple layers will outperform using only the last layer, which has been confirmed in the SUPERB benchmark. We did not test the performance of multiple layers, as emotion2vec already works well using the last layer. You can have a try if you're interested :)

**Comment by hayeong0** [comment]
I see, thanks for the kind response.
Thank you again for sharing your excellent work :)

**Comment by hayeong0** [comment]
I see, thanks for the kind response.
Thank you again for sharing your excellent work :)
