### ISSUE TITLE
fairseq version

### ISSUE THREAD

**Issue by niuqingyu** [ddlBoJack/emotion2vec#53]
Do you have any specific requirements for the Fairseq version? If so, what version should I download?

**Comment by ddlBoJack** [comment]
please use 0.12.2 version

**Comment by niuqingyu** [comment]
The conflict is caused by:
   fairseq 0.12.2 depends on omegaconf<2.1
   hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

---- Replied Message ----
| From | Ziyang ***@***.***> |
| Date | 11/10/2024 15:49 |
| To | ddlBoJack/emotion2vec ***@***.***> |
| Cc | niuqingyu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ddlBoJack/emotion2vec] fairseq version (Issue #53) |

please use 0.12.2 version
