### ISSUE TITLE
funasr

### ISSUE THREAD

**Issue by MF-XU** [ddlBoJack/emotion2vec#59]
Hello, I have been using your project to extract iemocap data set recently. I want to use the large version to extract it, but I can only use funasr for reasoning. In this process, funasr reasoning will directly make emotional judgment, and npy files cannot be generated for saving. Is there anything I can do.

**Comment by LauraGPT** [comment]
just set `extract_embedding=True` via funasr

**Comment by MF-XU** [comment]
> just set `extract_embedding=True` via funasr

Okay, thank you.
