### ISSUE TITLE
utterance embedding

### ISSUE THREAD

**Issue by ght0707** [ddlBoJack/emotion2vec#6]
How are utterance embedding obtained? Are they obtained from frame-level features through convolution or pooling?

**Comment by ddlBoJack** [comment]
We obtain utterance embedding by pooling only. You can also train your own aggregation module with your data.

**Comment by ght0707** [comment]
Thanks for the answer to your last question. When will the model pre-training process be updated please?
&nbsp;
&nbsp;
------------------ Original ------------------
From: &nbsp;"Ziyang ***@***.***&gt;;
Date: &nbsp;Wed, Jan 3, 2024 03:44 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ddlBoJack/emotion2vec] utterance embedding (Issue #6)

&nbsp;



 
We obtain utterance embedding by pooling only. You can also train your own aggregation module with your data.
