### ISSUE TITLE
OOM while processing IEMOCAP dataset

### ISSUE THREAD

**Issue by AirHorizons** [ddlBoJack/emotion2vec#7]
I was trying to create iemocap embedding on my own, but my GPU with 8GB memory gave me OOM from cuda. How much size do I need to process this?

**Comment by ddlBoJack** [comment]
Hi, for feature extraction using emotion2vec, the maximum GPU memory usage is only 2-3GB. You can check again to see if there is anything wrong.

**Comment by AirHorizons** [comment]
Good news I found my mistake when I put the audio file of the whole dialogue instead of each utterance. Thank you for assuring me to look for another way!
